### PR TITLE
Update Command_wipeflatlands.java

### PR DESCRIPTION
**Pull request by adroition**

### CODE REVIEW

**Comment by DUFCLiam** [comment]
Denied, This can be used to rogue in-game but in Telnet/Main console/Panel it can be traced, As that logs it to a file.

**Comment by PuggyCrew** [comment]
@DUFCLiam 
Excuse me?
This was just accepted by @rovertdude

**Comment by FoxIshDaBest** [comment]
SuperAdmins and Telnets can use /gcmd to force a senior to run this command. I suggest leaving this for only console to run.

**Comment by DUFCLiam** [comment]
Agreed

**Comment by rovertdude** [comment]
Good point of that.

**Comment by rovertdude** [comment]
Denied for @FoxIshDaBest and @DUFCLiam 's reasonings

**Pull request closed without merging**
