### PR TITLE
Block rogue /wildcard commands

### PR DESCRIPTION
**Pull request by adroition**
I mainly blocked some commands in /wildcard that can be used by rogue administrators.

### CODE REVIEW

**Comment by rovertdude** [comment]
Won't compile and needs testing, this is high priority as these new blocked wildcards are being used and are used a LOT.
I will manually make this go in the PFM if I have to.
The PFM v1.2 can wait, this is a very high priority issue.

**Comment by PuggyCrew** [comment]
Tested, it works, but won't compile.

**Comment by adroition** [comment]
Compiles now.

**Comment by rovertdude** [comment]
It should be compiling soon.
This is critical priority.

**Comment by rovertdude** [comment]
It won't merge or compile.
WE NEED THIS FIXED. CRITICAL PRIORITY.

**Comment by ownre** [comment]
Boy, you have such a bad bug here.

Patch has been made.

-ownre

**Comment by rovertdude** [comment]
Thanks SO MUCH @ownre

**Pull request merged**
