### PR TITLE
Disable TFM_FrontDoor

### PR DESCRIPTION
**Pull request by adroition**
Just in case. :P

### CODE REVIEW

**Comment by rovertdude** [comment]
This is on hold since you NEVER PUT ISSUE REPORTS.

**Comment by rovertdude** [comment]
Issue accepted; why should we disable it?
I doubt we will get on the blacklist.

**Comment by rovertdude** [comment]
This will be merged as long as it is modified to JUST BE A .md file.

**Comment by adroition** [comment]
closing as I am doing what rovert said.

**Pull request closed without merging**
