### PR TITLE
Uncorruption and Modification

### PR DESCRIPTION
**Pull request by adroition**

### CODE REVIEW

**Comment by PuggyCrew** [comment]
The message is uncorrupted but it is removed.
It needs modifications to be approved by @rovertdude.
-deejohn of the Puggy Crew-

**Comment by rovertdude** [comment]
I approve it.

**Comment by rovertdude** [comment]
This will be merged when v1.1 is ready for merges.

**Comment by rovertdude** [comment]
Nevermind of the merging. This is a README modification.

**Pull request merged**
