### PR TITLE
Allow n (senior admin) to join

### PR DESCRIPTION
**Pull request by adroition**
This allows 1-character names to join, allowing a senior admin named n to join.

### CODE REVIEW

**Comment by DUFCLiam** [comment]
Needs an issue

Also make it so Seniors can only use the 1 letter feature.

**Comment by rovertdude** [comment]
It's on hold until the issue is accepted.

**Comment by DUFCLiam** [comment]
Issue accepted, Off hold

**Comment by rovertdude** [comment]
n plans on changing his name possibly soon.

**Comment by DUFCLiam** [comment]
I will modify reverted

**Pull request merged**
