### PR TITLE
Um yeah u are in violation of TFM for the releases

### PR DESCRIPTION
**Pull request by falceso**
@Duckeroo I would recommend you removed the .jar before @jeromsar comes down. I am not the intended person to force you but I recommend you follow what I said. I'm just helping....

### CODE REVIEW

**Comment by falceso** [comment]
Also I'm going to take the free pugfreedommod XD

**Comment by rovertdude** [comment]
@falceso I own the PFM; I'll go and remove it.

**Comment by JeromSar** [comment]
@rovertdude You might own PFM, but you have a license to use my coprighted work. Only under the license provided can you use my work.

**Comment by rovertdude** [comment]
Didn't mean it like I owned the license, sorry if it seemed rude or something else from it.

**Pull request closed without merging**
