### PR TITLE
Update Command_overlord.java

### PR DESCRIPTION
**Pull request by adroition**

### CODE REVIEW

**Comment by PuggyCrew** [comment]
Not really needed.

**Comment by rovertdude** [comment]
I vouch.
People must know this is a command if they use it.

**Comment by adroition** [comment]
Acceptance?

**Comment by rovertdude** [comment]
It won't compile.

**Comment by adroition** [comment]
Fixed.

**Comment by rovertdude** [comment]
Merged as this is very minor.

**Pull request closed without merging**
