### PR TITLE
Update Command_saconfig.java

### PR DESCRIPTION
**Pull request by adroition**
#48

### CODE REVIEW

**Comment by adroition** [comment]
It is very needed; @rovertdude has always told me about /saconfig add ingame.

**Comment by DUFCLiam** [comment]
Wait, DO not merge

**Comment by DUFCLiam** [comment]
Needs modification.

**Comment by rovertdude** [comment]
I won't yet.
This is quite needed as only host console at first can use /saconfig add as we don't have telnet.

**Comment by rovertdude** [comment]
Senior administrators will be allowed to use it as he has made it in this PR.

**Comment by DUFCLiam** [comment]
Nvm, accepted.

**Comment by DUFCLiam** [comment]
Lock conversation?

**Comment by rovertdude** [comment]
If you want, just don't close it yet.

**Comment by PuggyCrew** [comment]
When will v1.2 be merging more?
This should be added right now.

**Comment by rovertdude** [comment]
Thanks for the PR! v1.2 will be merging for now.

**Pull request merged**
