### PR TITLE
Remove DUFCLiam from the developer list

### PR DESCRIPTION
**Pull request by adroition**
There's no need for him to be in it.

### CODE REVIEW

**Comment by rovertdude** [comment]
Why remove him? He can be helpful in this.

**Comment by ownre** [comment]
He shouldn't be removed.

**Comment by PuggyCrew** [comment]
He isn't a collaborator or anything yet; he shouldn't be dev.

**Comment by DUFCLiam** [comment]
Well, I have been helpful and may be a collaborator soon =D So I would suggest putting this on hold and removing Ready to merge

**Comment by rovertdude** [comment]
Denied as @DUFCLiam is now a collaborator (or at least will be soon)

**Pull request closed without merging**
