### PR TITLE
Revert "Patch"

### PR DESCRIPTION
**Pull request by DUFCLiam**
Reverts rovertdude/PugFreedomMod#11

### CODE REVIEW

**Comment by rovertdude** [comment]
/toggle is meant to be used ingame.

**Comment by DUFCLiam** [comment]
But, it can be abused to crash the server

**Comment by rovertdude** [comment]
If a superadmin honestly wanted to, they can /stop the server which will probably be modified soon.

**Comment by rovertdude** [comment]
./toggle can only be used by super admins and when the TFM/PFM is reloaded, it auto disables any changes unless it's in the config.
@Duckeroo

**Comment by DUFCLiam** [comment]
Ok, denied.

**Pull request closed without merging**
