### PR TITLE
Update TFM_PlayerRank.java

### PR DESCRIPTION
**Pull request by DUFCLiam**

### CODE REVIEW

**Comment by rovertdude** [comment]
Thanks; this will probably help with anything with copyright.

**Comment by DUFCLiam** [comment]
:P Ikr @rovertdude I wanna be Lad-Dev xD

**Comment by rovertdude** [comment]
@DUFCLiam 
xD

**Comment by DUFCLiam** [comment]
@rovertdude Can you make me an organization owner? Please, I will make this comply with the licencce

**Comment by PuggyCrew** [comment]
@DUFCLiam 
I'll talk to rovert about making you a contributor like I am.

**Comment by DUFCLiam** [comment]
:)

**Pull request merged**
