### PR TITLE
Limit host console

### PR DESCRIPTION
**Pull request by adroition**

### CODE REVIEW

**Comment by DUFCLiam** [comment]
I  forgot what LimitHsotConsole means feeling sick and banged head D=

**Comment by adroition** [comment]
@DUFCLiam 
The host console is unable to use this command.

**Comment by DUFCLiam** [comment]
Ok.

**Comment by PuggyCrew** [comment]
Nice find of that.

**Comment by rovertdude** [comment]
Thanks for the PR!

**Pull request merged**
